# Generated by Django 4.0.6 on 2022-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_alter_intern_form_formstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SHORTLISTED', 'shortlisted'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
    ]
