# Generated by Django 4.0.6 on 2022-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0009_alter_internapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_form',
            name='FormStatus',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('SHORTLISTED', 'shortlisted'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
    ]
