# Generated by Django 4.0.6 on 2022-07-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0010_alter_intern_form_formstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_form',
            name='FormStatus',
            field=models.CharField(choices=[('DEACTIVE', 'DEACTIVE'), ('ACTIVE', 'ACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('SHORTLISTED', 'shortlisted'), ('PENDING', 'pending'), ('REJECTED', 'rejected')], default='PENDING', max_length=20),
        ),
    ]
