# Generated by Django 4.0.6 on 2022-07-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0013_alter_internapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('SHORTLISTED', 'shortlisted'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
